apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::468428427679:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-cjNp0I1gpEsg
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::468428427679:user/ramesh
      username: ramesh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::468428427679:user/raheem
      username: raheem    
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-04T09:39:05Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1273"
  uid: 3d92e3fc-3a6a-4c5c-afee-4430288f762e

